name = "web-mcp-demo"
main = "./worker.ts"
compatibility_date = "2026-09-01"
compatibility_flags = ["nodejs_compat", "enable_nodejs_http_modules"]
keep_vars = true

[assets]
directory = "./out"
binding = "ASSETS"
run_worker_first = ["/api/*"]
