const DISPOSABLE_DOMAINS = new Set([
  '0-mail.com', '0815.ru', '0clickemail.com', '10minutemail.com', '20minutemail.com',
  'anonbox.net', 'binkmail.com', 'bobmail.info', 'bofthew.com', 'bugmenot.com',
  'bumpymail.com', 'casualdx.com', 'chacuo.net', 'clipmail.eu', 'crazymailing.com',
  'cuirmail.com', 'dayrep.com', 'deadaddress.com', 'despammed.com', 'devnullmail.com',
  'discard.email', 'discardmail.com', 'discardmail.de', 'disposable.email',
  'disposableaddress.com', 'disposableemailaddresses.emailmiser.com', 'disposableinbox.com',
  'dispose.it', 'dispostable.com', 'dm.w3internet.co.uk', 'dodgeit.com', 'dodgit.com',
  'drdrb.net', 'dropmail.me', 'dumpandjunk.com', 'dumpmail.de', 'duskmail.com',
  'e4ward.com', 'emaildienst.de', 'emailgo.de', 'emailigo.de', 'emailisvalid.com',
  'emailmiser.com', 'emailsensei.com', 'emailtemporario.com.br', 'emailthe.net',
  'emailtmp.com', 'emailwarden.com', 'emailx.at.hm', 'emailxfer.com', 'emz.net',
  'ero-tube.org', 'evopo.com', 'explodemail.com', 'fakeinbox.com',
  'fakeinformation.com', 'fakemail.fr', 'fakemailz.com', 'fammix.com', 'fastacura.com',
  'filzmail.com', 'fixmail.tk', 'flyspam.com', 'frapmail.com', 'front14.org',
  'fux0ringduh.com', 'garliclife.com', 'get1mail.com', 'get2mail.fr', 'getairmail.com',
  'getmails.eu', 'getonemail.com', 'getonemail.net', 'ghosttexter.de', 'girlsundertheinfluence.com',
  'gishpuppy.com', 'goemailgo.com', 'gotmail.net', 'gotmail.org', 'gotti.otherinbox.com',
  'great-host.in', 'greensloth.com', 'grr.la', 'gsrv.co.uk', 'guerrillamail.biz',
  'guerrillamail.com', 'guerrillamail.de', 'guerrillamail.info', 'guerrillamail.net',
  'guerrillamail.org', 'guerrillamailblock.com', 'gustr.com', 'harakirimail.com',
  'hat-gansen.de', 'hatespam.org', 'herp.in', 'hidemail.de', 'hidzz.com',
  'hmamail.com', 'hopemail.biz', 'ieh-mail.de', 'ikbenull.com', 'imails.info',
  'inbax.tk', 'inbox.si', 'inboxalias.com', 'inboxclean.com', 'inboxclean.org',
  'incognitomail.com', 'incognitomail.net', 'incognitomail.org', 'insorg-mail.info',
  'ipoo.org', 'irish2me.com', 'iwi.net', 'jetable.com', 'jetable.fr.nf',
  'jetable.net', 'jetable.org', 'jnxjn.com', 'jourrapide.com', 'jsrsolutions.com',
  'kasmail.com', 'kaspop.com', 'keepmymail.com', 'killmail.com', 'killmail.net',
  'kir.ch.tc', 'klassmaster.com', 'klassmaster.net', 'klzlk.com', 'koszmail.pl',
  'kurzepost.de', 'lawlita.com', 'letthemeatspam.com', 'lhsdv.com', 'lifebyfood.com',
  'link2mail.net', 'litedrop.com', 'lol.ovpn.to', 'lookugly.com', 'lopl.co.cc',
  'lortemail.dk', 'lr78.com', 'lroid.com', 'lukop.dk', 'm21.cc',
  'mail-hierarchie.de', 'mail-temporaire.fr', 'mail.by', 'mail.mezimages.net',
  'mail.zp.ua', 'mail1a.de', 'mail21.cc', 'mail2rss.org', 'mail333.com',
  'mailbidon.com', 'mailblocks.com', 'mailblog.biz', 'mailbucket.org', 'mailcat.biz',
  'mailcatch.com', 'mailde.de', 'mailde.info', 'maildrop.cc', 'maildx.com',
  'maileater.com', 'mailexpire.com', 'mailfa.tk', 'mailforspam.com', 'mailfree.ga',
  'mailfreeonline.com', 'mailfs.com', 'mailguard.me', 'mailhazard.com', 'mailhazard.us',
  'mailhz.me', 'mailimate.com', 'mailin8r.com', 'mailinater.com', 'mailinator.com',
  'mailinator.net', 'mailinator.org', 'mailinator2.com', 'mailincubator.com',
  'mailismagic.com', 'mailmate.com', 'mailme.ir', 'mailme.lv', 'mailme24.com',
  'mailmetrash.com', 'mailmoat.com', 'mailms.com', 'mailnator.com', 'mailnesia.com',
  'mailnull.com', 'mailorg.org', 'mailpick.biz', 'mailproxsy.com', 'mailquack.com',
  'mailrock.biz', 'mailscrap.com', 'mailshell.com', 'mailsiphon.com', 'mailslite.com',
  'mailtemp.info', 'mailtothis.com', 'mailtrash.net', 'mailtv.net', 'mailtv.tv',
  'mailzilla.com', 'mailzilla.org', 'makemetheking.com', 'manifestgenerator.com',
  'mbx.cc', 'mega.zik.dj', 'meinspamschutz.de', 'meltmail.com', 'messagebeamer.de',
  'mezimages.net', 'ministry-of-silly-walks.de', 'mintemail.com', 'misterpinball.de',
  'mmmmail.com', 'moakt.com', 'mobi.web.id', 'mobileninja.co.uk', 'mohmal.com',
  'moncourrier.fr.nf', 'monemail.fr.nf', 'monmail.fr.nf', 'monumentmail.com',
  'msa.minsmail.com', 'mt2015.com', 'mx0.wwwnew.eu', 'my10telemail.com',
  'mycard.net.ua', 'mycleaninbox.net', 'myemailboxy.com', 'mymail-in.net',
  'mypacks.net', 'mypartyclip.de', 'myphantom.com', 'mysamp.de', 'myspaceinc.com',
  'myspaceinc.net', 'myspaceinc.org', 'myspacepimpedup.com', 'mytemp.email',
  'mytempmail.com', 'mytrashmail.com', 'nabala.com', 'neomailbox.com',
  'nepwk.com', 'nervmich.net', 'nervtansen.de', 'netmails.com', 'netmails.net',
  'neverbox.com', 'no-spam.ws', 'nobulk.com', 'noclickemail.com', 'nogmailspam.info',
  'nomail.xl.cx', 'nomail2me.com', 'nomorespamemails.com', 'nospam.ze.tc',
  'nospam4.us', 'nospamfor.us', 'nospammail.net', 'nothingtoseehere.ca',
  'nowmymail.com', 'nurfuerspam.de', 'nus.edu.sg', 'nwldx.com',
  'objectmail.com', 'obobbo.com', 'odnorazovoe.ru', 'oneoffemail.com',
  'onewaymail.com', 'oopi.org', 'ordinaryamerican.net', 'otherinbox.com',
  'ourklips.com', 'outlawspam.com', 'ovpn.to', 'owlpic.com',
  'pancakemail.com', 'pimpedupmyspace.com', 'pjjkp.com', 'plexolan.de',
  'pookmail.com', 'privacy.net', 'proxymail.eu', 'prtnx.com', 'punkass.com',
  'putthisinyourspamdatabase.com', 'qq.com', 'quickinbox.com',
  'rcpt.at', 'reallymymail.com', 'recode.me', 'recursor.net',
  'regbypass.com', 'rejectmail.com', 'rhyta.com', 'rklips.com',
  'rmqkr.net', 'royal.net', 'rppkn.com', 'rtrtr.com', 'ruffrey.com',
  's0ny.net', 'safe-mail.net', 'safersignup.de', 'safetymail.info',
  'safetypost.de', 'sandelf.de', 'saynotospams.com', 'scatmail.com',
  'schafmail.de', 'schizofrenia.ch', 'selfdestructingmail.com', 'sendspamhere.com',
  'shiftmail.com', 'shitmail.me', 'shortmail.net', 'sibmail.com',
  'skeefmail.com', 'slaskpost.se', 'slipry.net', 'slopsbox.com',
  'slowslow.de', 'slutty.horse', 'smashmail.de', 'smellfear.com',
  'snakemail.com', 'sneakemail.com', 'sneakyads.com', 'sofimail.com',
  'sofort-mail.de', 'softpls.asia', 'sogetthis.com', 'soodonims.com',
  'spam.la', 'spam.su', 'spam4.me', 'spamavert.com', 'spambob.com',
  'spambob.net', 'spambob.org', 'spambog.com', 'spambog.de', 'spambog.ru',
  'spambox.us', 'spamcannon.com', 'spamcannon.net', 'spamcero.com',
  'spamcorptastic.com', 'spamcowboy.com', 'spamcowboy.net', 'spamcowboy.org',
  'spamday.com', 'spamex.com', 'spamfighter.cf', 'spamfighter.ga',
  'spamfighter.gq', 'spamfighter.ml', 'spamfighter.tk', 'spamfree24.com',
  'spamfree24.de', 'spamfree24.eu', 'spamfree24.info', 'spamfree24.net',
  'spamfree24.org', 'spamgoes.in', 'spamgourmet.com', 'spamgourmet.net',
  'spamgourmet.org', 'spamherelots.com', 'spamhereplease.com', 'spamhole.com',
  'spamify.com', 'spaminator.de', 'spamkill.info', 'spaml.com', 'spaml.de',
  'spammotel.com', 'spamobox.com', 'spamoff.de', 'spamslicer.com',
  'spamspot.com', 'spamstack.net', 'spamthis.co.uk', 'spamtrap.ro',
  'spamtrail.com', 'spamwc.de', 'speed.1s.fr', 'spoofmail.de',
  'stuffmail.de', 'supergreatmail.com', 'supermailer.jp', 'superrito.com',
  'superstachel.de', 'suremail.info', 'svk.jp', 'sweetxxx.de',
  'tafmail.com', 'tagyoureit.com', 'talkinator.com', 'tapchicuoihoi.com',
  'teewars.org', 'teleworm.com', 'teleworm.us', 'temp-mail.org',
  'temp-mail.ru', 'tempalias.com', 'tempe4mail.com', 'tempemail.co.za',
  'tempemail.com', 'tempemail.net', 'tempinbox.com', 'tempinbox.co.uk',
  'tempmail.eu', 'tempmail.it', 'tempmail2.com', 'tempmaildemo.com',
  'tempmailer.com', 'tempmailer.de', 'tempomail.fr', 'temporarily.de',
  'temporarioemail.com.br', 'temporaryemail.net', 'temporaryemail.us',
  'temporaryforwarding.com', 'temporaryinbox.com', 'temporarymailaddress.com',
  'tempthe.net', 'thankdog.com', 'thankyou2010.com', 'thc.st',
  'thecriminals.com', 'thisisnotmyrealemail.com', 'thismail.net',
  'throwawayemailaddress.com', 'tilien.com', 'tittbit.in', 'tizi.com',
  'tmailinator.com', 'toiea.com', 'toomail.biz', 'topranklist.de',
  'tradermail.info', 'trash-amil.com', 'trash-mail.at', 'trash-mail.com',
  'trash-mail.de', 'trash2009.com', 'trashdevil.com', 'trashemail.de',
  'trashmail.at', 'trashmail.com', 'trashmail.de', 'trashmail.io',
  'trashmail.me', 'trashmail.net', 'trashmail.org', 'trashmail.ws',
  'trashmailer.com', 'trashymail.com', 'trashymail.net', 'trbvm.com',
  'trbvn.com', 'trialmail.de', 'trickmail.net', 'trillianpro.com',
  'turual.com', 'twinmail.de', 'tyldd.com', 'uggsrock.com',
  'umail.net', 'upliftnow.com', 'uplipht.com', 'venompen.com',
  'veryreallymymail.com', 'viditag.com', 'viewcastmedia.com',
  'viewcastmedia.net', 'viewcastmedia.org', 'vomoto.com', 'vpn.st',
  'vsimcard.com', 'vubby.com', 'wasteland.rfc822.org', 'webemail.me',
  'weg-werf-email.de', 'wegwerfadresse.de', 'wegwerfemail.com',
  'wegwerfemail.de', 'wegwerfmail.de', 'wegwerfmail.net', 'wegwerfmail.org',
  'wh4f.org', 'whyspam.me', 'wickmail.net', 'wilemail.com',
  'willhackforfood.biz', 'willselfdestruct.com', 'winemaven.info',
  'wronghead.com', 'wuzup.net', 'wuzupmail.net', 'wwwnew.eu',
  'x.ip6.li', 'xagloo.com', 'xemaps.com', 'xents.com',
  'xjoi.com', 'xmaily.com', 'xoxy.net', 'yapped.net',
  'yeah.net', 'yep.it', 'yogamaven.com', 'yomail.info',
  'yopmail.com', 'yopmail.fr', 'yopmail.net', 'yourdomain.com',
  'ypmail.webarnak.fr.eu.org', 'yuurok.com', 'zehnminutenmail.de',
  'zippymail.info', 'zoaxe.com', 'zoemail.org',
])

export function isDisposableEmail(email: string): boolean {
  const domain = email.split('@')[1]?.toLowerCase()
  if (!domain) return false
  return DISPOSABLE_DOMAINS.has(domain)
}
